# render.yaml
services:
  - type: web
    name: CodeSentry
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: GITHUB_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MOCK_MODE
        value: "false"